repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-lint
        name: ruff lint
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      - id: pyrefly
        name: pyrefly type check
        entry: uv run pyrefly check src/
        language: system
        pass_filenames: false
        always_run: true
